INSERT INTO movimientos (nombre, danio) VALUES ('Ataque Rápido', 40);
INSERT INTO movimientos (nombre, danio) VALUES ('Rabia', 20);
INSERT INTO movimientos (nombre, danio) VALUES ('Autodestrucción', 200);
INSERT INTO movimientos (nombre, danio) VALUES ('Bombazo Huevo', 100);
INSERT INTO movimientos (nombre, danio) VALUES ('Látigo', 20);
INSERT INTO movimientos (nombre, danio) VALUES ('Polución', 20);
INSERT INTO movimientos (nombre, danio) VALUES ('Lodo', 65);
INSERT INTO movimientos (nombre, danio) VALUES ('Hueso Palo', 65);
INSERT INTO movimientos (nombre, danio) VALUES ('Llamarada', 110);
INSERT INTO movimientos (nombre, danio) VALUES ('Cascada', 80);
INSERT INTO movimientos (nombre, danio) VALUES ('Oscuro', 35);
INSERT INTO movimientos (nombre, danio) VALUES ('Rapidez', 60);
INSERT INTO movimientos (nombre, danio) VALUES ('Escudo', 100);
INSERT INTO movimientos (nombre, danio) VALUES ('Cañonazo', 20);
INSERT INTO movimientos (nombre, danio) VALUES ('Restricción', 10);
INSERT INTO movimientos (nombre, danio) VALUES ('Patada Salto', 130);
INSERT INTO movimientos (nombre, danio) VALUES ('Comesueños', 100);
INSERT INTO movimientos (nombre, danio) VALUES ('Golpe Aéreo', 140);
INSERT INTO movimientos (nombre, danio) VALUES ('Burbuja', 40);
INSERT INTO movimientos (nombre, danio) VALUES ('Martillazo', 90);
INSERT INTO movimientos (nombre, danio) VALUES ('Explosión', 250);
INSERT INTO movimientos (nombre, danio) VALUES ('Huesomerang', 50);
INSERT INTO movimientos (nombre, danio) VALUES ('Tumba Rocas', 75);
INSERT INTO movimientos (nombre, danio) VALUES ('Hipercolmillo', 80);
INSERT INTO movimientos (nombre, danio) VALUES ('Triataque', 80);
INSERT INTO movimientos (nombre, danio) VALUES ('Corte', 70);
INSERT INTO movimientos (nombre, danio) VALUES ('Combate', 50);